name: ml_venv
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - pip=23.1.2
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - xgboost=1.7.6